"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var person_1 = require("./person");
var person1 = new person_1.Person("Alice", 30, "Wonderland University", 101);
console.log(person1.greet());
console.log("Person ID:", person1.showId());
console.log("Person Counter:", person_1.Person.counter);
var student1 = new person_1.Student("Bob", 20, "Builder Institute", 1, ["JavaScript", "TypeScript"]);
console.log(student1.getStudentDetails());
student1.addskill("React");
student1.display();
console.log("Person Counter after creating Student:", person_1.Person.counter);
